on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check & Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.88.0 # Rust MSRV
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        run: rustup set profile minimal && rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Check
        run: cargo check --verbose
      - name: Test
        run: cargo test --workspace

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.88.0 # Rust MSRV
    steps:
      - uses: actions/checkout@v6
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - run: cargo clippy --all-targets -- -D warnings
