name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends musl-tools
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -Ccodegen-units=1 -Clink-arg=-Wl,-z,relro
        with:
          command: build
          args: --verbose --release --target x86_64-unknown-linux-musl
      - name: Prepare package
        run: |
          G_TAG=${{ github.ref }}
          G_VERSION=${G_TAG#refs/tags/v}
          DIST_DIR="thumbs-$G_VERSION-x86_64-unknown-linux-musl"
          TARGET_FILE="$DIST_DIR.tar.gz"
          rm -rf "$DIST_DIR"
          mkdir -p "$DIST_DIR"
          cp -p target/x86_64-unknown-linux-musl/release/thumbs "$DIST_DIR"
          cp -p README.md "$DIST_DIR"
          cp -p CHANGELOG.md "$DIST_DIR"
          cp -p LICENSE "$DIST_DIR"
          cp -p NOTICE "$DIST_DIR"
          cp -rp extra "$DIST_DIR"
          strip "$DIST_DIR/thumbs"
          tar -czf "$TARGET_FILE" "$DIST_DIR"
          sha256sum "$TARGET_FILE" > "$TARGET_FILE.sha256"
          echo "G_VERSION=$G_VERSION" >> $GITHUB_ENV
      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: thumbs ${{ env.G_VERSION }}
          draft: true
          body_path: CHANGELOG.md
          files: |
            *.tar.gz
            *.tar.gz.sha256
